"""add_address_fields_to_orders

Revision ID: 273c63689c14
Revises: 4e931faa1472
Create Date: 2026-02-05 11:31:48.954756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273c63689c14'
down_revision: Union[str, Sequence[str], None] = '4e931faa1472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('street', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('house_number', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('postal_code', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('city', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('country', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'country')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'postal_code')
    op.drop_column('orders', 'house_number')
    op.drop_column('orders', 'street')
    # ### end Alembic commands ###
